---
title: "Data setup"
output:
  html_document:
    theme: 
      version: 5
      bootswatch: default
    highlight: arrow
    highlight_downlit: true
    mathjax: null
    css: "rmd.css"
    md_extensions: "-smart"
---

```{r, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{r}
library(tidyverse)
library(pins)
library(pinsqs)
library(AzureStor)

source("R/azure_init.R")

speeches_board <- storage_endpoint("https://cbspeeches1.dfs.core.windows.net/", token=token) %>%
  storage_container(name = "cbspeeches") %>%
  board_azure(path = "data-speeches")
```

Read in speeches from the Dropbox:

```{r}
speeches <- read_csv("~/boc_speeches/lda/iteration_04/speeches_processed.csv")
```

Perform some minor adjustments:

- Rename the column `processed_text` to simply `text`.
- Remove the time component of the dates.
- Perform normalization of text and author names to their ASCII form.

```{r}
speeches <- speeches %>%
  rename(text = processed_text) %>%
  mutate(
    date = as_date(date),
    text = stringi::stri_trans_general(text, "Greek-Latin"),
    text = stringi::stri_trans_general(text, "Latin-ASCII"),
    author = stringi::stri_trans_general(author, "Greek-Latin"),
    author = stringi::stri_trans_general(author, "Latin-ASCII")
  )
```

Write the raw data to the pin board:

```{r}
speeches_board %>%
  pin_qsave(
    speeches,
    "speeches-raw",
    title = "speeches from dropbox with minor tweaks"
  )
```
